[package]
name = "rust-coding-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
serde = { version = "1.0.140", features = ["derive"] }
lazy_static = "1.4.0"
